# Generated by Django 4.0.4 on 2022-05-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_alter_kino_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhanr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='жанр')),
            ],
        ),
        migrations.CreateModel(
            name='ZhanrKino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kino')),
                ('zhanr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.zhanr')),
            ],
        ),
    ]
