# Generated by Django 4.0.4 on 2022-05-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_zhanr_zhanrkino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhanrkino',
            name='zhanr',
        ),
        migrations.AddField(
            model_name='kino',
            name='zhanr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.zhanr'),
        ),
    ]
