# Generated by Django 4.0.4 on 2022-05-30 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_kino_zhanr'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhanrkino',
            name='zhanr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.zhanr'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='zhanr',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.zhanr'),
        ),
    ]
