# Generated by Django 4.0.4 on 2022-05-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_zhanrkino_zhanr_alter_kino_zhanr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='zhanr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.zhanr'),
        ),
    ]
