# Generated by Django 4.0.4 on 2022-05-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_kino_zhanr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhanrkino',
            name='zhanr',
        ),
    ]
