# Generated by Django 4.0.4 on 2022-05-30 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_kino_zhanr_kino_one_kino_three_kino_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название студии')),
            ],
        ),
        migrations.AddField(
            model_name='kino',
            name='studio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='main.studio'),
        ),
    ]
