# Generated by Django 4.0.4 on 2022-05-30 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studio_kino_studio'),
    ]

    operations = [
        migrations.CreateModel(
            name='KinoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=40, verbose_name='выберите тип')),
            ],
        ),
        migrations.AddField(
            model_name='kino',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='main.kinotype'),
        ),
    ]
