# Generated by Django 4.0.4 on 2022-06-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_kinotype_kino_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
