# Generated by Django 3.2.8 on 2022-06-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220604_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='genres',
            field=models.ManyToManyField(default=None, to='main.Zhanr'),
        ),
    ]
